#pragma once

#include <stdint.h>

/*
 * Resultado detallado de una orden.
 */
enum class CommandResultCode : uint8_t {
    ACCEPTED = 0,

    RELAY_NOT_FOUND,
    RELAY_NOT_INITIALIZED,
    RELAY_DISABLED,
    RELAY_SAFETY_LOCKED,
    RELAY_FAULTED,

    INVALID_COMMAND,
    CONTROL_SOURCE_NOT_ALLOWED,
    INVALID_DURATION,
    TIMED_COMMAND_REQUIRED,
    DURATION_EXCEEDS_MAXIMUM,
    MIN_OFF_DURATION_NOT_ELAPSED,

    SCHEDULE_CONTROL_NOT_ALLOWED,
    AUTOMATION_CONTROL_NOT_ALLOWED,

    ACTIVE_TIMER_EXISTS,
    TIMER_CAPACITY_REACHED,

    COMMAND_EXECUTION_FAILED
};